apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
# kubectl → API Server → Scheduler → Node → Pod → Container
# kubectl apply -f pods/nginx-pod.yaml
# kubectl get pods
# kubectl describe pod nginx-pod
# kubectl logs nginx-pod
# kubectl delete pod nginx-pod
# kubectl get pods
# kubectl delete deployment nginx-deployment